### ISSUE TITLE
Unable to trigger Local Notification IOS 11

### ISSUE THREAD

**Issue by BeMontelli** [katzer/cordova-plugin-local-notifications#1527]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

Provide a general summary of the issue.

## Your Environment

* Plugin version: 0.8.4 (unable to run 0.9 - Build Failed)
* Platform: Cordova / AngularJS
* OS version: IOS 11
* Device manufacturer / model: All IOS 11 Devices
* Cordova version (```cordova -v```): 7.0.0
* Cordova platform version (```cordova platform ls```):  android 6.1.2 / ios 4.3.1,
* Plugin config: no specific config

## Expected Behavior

I should be able to display local notifications on IOS 11 (I guess)

## Actual Behavior

The notifications are not displayed even if they are scheduled on IOS 11 (Works on IOS 9)

## Context

I use XCode in my Cordova Project to build and publish my app. Android version works but i have errors to run local notification with IOS 11 ( Xcode emulator or real Device "Iphone5S )

## Steps to Reproduce

  1. XCode Compilation is ok
  2. Launch Appli is ok
  3. When launching Notification, Xcode Launch exceptions (Following)

## Debug logs

Xcode Console gave me these indications:
- `cordova.plugins.notification.local.hasPermission` is `true` after popup permission agreement
- but firing notification i have `Main Thread Checker: UI API called on a background thread: -[UIApplication cancelLocalNotification`and `APPLocalNotification cancelForerunnerLocalNotification`

Here is my notifications tests:

```
cordova.plugins.notification.local.registerPermission(function (granted) {
      console.log('Permission has been granted: ' + granted);
      if(granted){
            cordova.plugins.notification.local.schedule({
                    id: '5465512318798',
                    title: 'TEST',
                    text: 'a test',
                    badge: 0
            });
     }
});
```
And, on IOS my schedule and trigger tests:

```
cordova.plugins.notification.local.on("schedule", function(notification) {
                        alert("scheduled: " + notification.id);
                    });
cordova.plugins.notification.local.on("trigger", function(notification) {
                        alert("triggered: " + notification.id);
                    });
cordova.plugins.notification.local.on("click", function(notification) {
                        alert("clicked: " + notification.id);
                    });
```

On android, each `.on` is triggered; on IOS i only have the `schedule` alert

  * ios XCode logs
  * Android: $ adb logcat

Thanks in advance for you help.

**Comment by Tawpie** [comment]
You have to set a time/date to trigger the notification in your .schedule else its difficult for the plugin to know when to trigger the notification. This is the at: property of the notification object.

Also, I personally recommend:

- cancel existing notifications and schedule the new notifications in the callback for the cancel
- put your notification objects in an array even if there's only one notification
- I use an integer for the id, not a string (I'm not certain if an int is required though)


This example is 0.8.x, not the latest plugin. It has been very stable but because it doesn't use the latest 0.9.x plugin may have developed some age-related problems. I apologize for the Hungarian notation, it's in our style guide.
```
// build a basic reminder
oKatzerLNPluginReminder = {
    id: i + 1,
    at: (new Date(dFireDate)),    // MUST be a date object
    text: oMessage.displaytext,
    title: oMessage.headline
    smallIcon: "res://sm_notif.png"
};

// lookup to see if sound is enabled, if not, turn it off
if (useNotificationSound() == 0) {
     oKatzerLNPluginReminder.sound = null;
}

// add metadata if we have it
if (typeof sMetaData !== 'undefined') {
    oKatzerLNPluginReminder.data = sMetaData; // Data to be passed through the notification
}

// add reminder object to the array for Katzer multiple scheduling
gaMultiRemindersForKatzerLNPlugin.push(oKatzerLNPluginReminder);                 

var iStartTime = (new Date()).getTime();    // for debug to check timing of cancel

// and finally schedule the reminders
if (gaMultiRemindersForKatzerLNPlugin.length) {
    cordova.plugins.notification.local.cancelAll(function scheduleAllRemindersViaKatzer() {
        // debug note, windows phone is notoriously slow in the cancel process
        console.log("lM.fQLM - cancellation completed. Elapsed: " + ((new Date()).getTime() - iStartTime) / 1000 + " secs");
        
        // schedule the notifications
        console.log(" lM.fQLM - scheduling >" + gaMultiRemindersForKatzerLNPlugin.length + "< local reminders");
        cordova.plugins.notification.local.schedule(gaMultiRemindersForKatzerLNPlugin);
} else {
console.warn(" lM.fQLM - there were no reminders in gaMultiRemindersForKatzerLNPlugin to schedule");
}
```

**Comment by rwillett** [comment]
There should be no problem getting the buiold working with IOS 11. You should be using the latest plugin for IOS anyway.

I would raise another issue with details of how trhe build fails as that shouldn't happen.

**Comment by BeMontelli** [comment]
Hello, first thanks for your answers !

I tried some ways to solve my probem but nothing changed.

Here is the complete code i tried:

```
if (window.hasOwnProperty('cordova')) {
    $timeout( function() {
        var notifications = [];
        var notificationUnique = {
            id: 123,
            at: (new Date()).getTime(),
            text: "text",
            title: "title"
// Is smallIcon: "res://sm_notif.png" needed in IOS ?
        };

        notificationUnique.sound = null;
        notificationUnique.data = null;

        notifications.push(notificationUnique);

        cordova.plugins.notification.local.registerPermission(function (granted) {
            if(granted){
                console.log("Permission : "+granted);
                if (notifications.length) {
                    console.log("Length Notifications : "+notifications.length);
                    cordova.plugins.notification.local.cancelAll(function () {
                        console.log("cancelAll");
                        cordova.plugins.notification.local.schedule(notifications);
                    });
                } else {
                    console.warn(" lM.fQLM - there were no reminders in notifications to schedule");
                }
            }
        });
    }, 0 );
}
```
More here is my Cordova config, could a compatibility plugin problem exist ? I first thank of `cordova-plugin-ionic-webview`but nothing changed when i removed it.

```
    <engine name="android" spec="^6.2.3" />
    <engine name="ios" spec="^4.4.0" />
    <plugin name="cordova-plugin-compat" spec="^1.1.0" />
    <plugin name="cordova-plugin-console" spec="^1.0.7" />
    <plugin name="cordova-plugin-geolocation" spec="^2.4.3" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.1" />
    <plugin name="cordova-plugin-ionic-webview" spec="~1.1.15" />
    <plugin name="cordova-plugin-local-notification" spec="~0.8.4" />
    <plugin name="cordova-plugin-network-information" spec="^1.3.3" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-sqlite-storage" spec="~2.1.2" />
```
Thanks you.

**Comment by BeMontelli** [comment]
The error i got in Xcode are always the same:

```
Main Thread Checker: UI API called on a background thread: -[UIApplication cancelAllLocalNotifications]
4                   0x0000000100dcd724 -[APPLocalNotification cancelAllLocalNotifications] + 76
5                   0x0000000100dcaee0 __34-[APPLocalNotification cancelAll:]_block_invoke + 52
-[UIApplication cancelAllLocalNotifications]
4                   0x0000000100dcd724 -[APPLocalNotification cancelAllLocalNotific5                     0x0000000100dcaee0 __34-[APPLocalNotification cancelAll:]_block_invoke + 52
4                   0x0000000100dcd76c -[APPLocalNotification cancelAllLocalNotifications] + 148
5                   0x0000000100dcaee0 __34-[APPLocalNotification cancelAll:]_block_invoke +4                      0x0000000100dcd76c -[APPLocalNotification cancelAllLocal5                      0x0000000100dcaee0 __34-[APPLocalNotification cancelAll:]_block_invoke + 52
7                   0x0000000100dcaf0c __34-[APPLocalNotification cancelAll:]_block_invoke + 96
7                   0x0000000100dcaf0c __34-[APPLocalNotification cancelAll:]_block_invoke + 92018-02-09 10:05:49.471044+0100 [2162:1354783] cancelAll
6                   0x0000000100dcd8ec -[APPLocalNotification cancelForerunnerLocalNotification:] + 196
6                   0x0000000100dcd8ec -[APPLocalNotification cancelForerunnerLocalNotification:] + 196
2018-02-09 10:05:53.438402+0100 [2162:1354783] cancelAll
```

**Comment by rwillett** [comment]
Something is very odd here.

1. We use Xcode 9.2 with the local notification plugin 9.0 Beta 2.  We target IOS 10 and IOS 11. We no longer target IOS 9 or below.

2. No build problems at all. It just works.

3. I would move to the latest plugin and get that working. The old one will not be supported and probably has issues anyway with IOS11. You will have to move at some time anyway so you might as well do it now.

4. What version of Xcode are you using?

5. What is your target version of IOS in Xcode?

6. Strip your code right back to the basics, dump the registerpermissions and make sure you have them.

7. Make sure the at: is inside a trigger object now. The format has changed for V0.9.

8. Add five seconds or something to the date object as it needs to be in the future. Saying 'now' is too quick.

9. Are you waiting for deviceready?

10. Is this an Ionic project? If so what version?

11. Your plugins look OK (ish). We don't use cordova-plugin-inappbrowser, cordova-plugin-compat, cordova-plugin-ionic-webview or cordova-plugin-geolocation. The rest look OK.

The latest version of the plugin works with Xcode 9.2 on IOS 10 and 11 with zero issues for us. I'm surprised you have these issues.

Rob

**Comment by rwillett** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/issues/1524 has working code to schedule four notifications. Use that as a template if needed.

**Comment by katzer** [comment]
@BeMontelli v0.8.x does not work for iOS10+ You will need to upgrade.

**Comment by BeMontelli** [comment]
I choosed to upgrade "cordova-plugin-local-notification" to the 0.9.0-beta.2 version
and now have these errors:

Android `cordova run android --device`:

```
Command failed with exit code 1 Error output:
/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:25: error: cannot find symbol
import android.app.NotificationChannel;
                  ^
  symbol:   class NotificationChannel
  location: package android.app
/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:43: error: cannot find symbol
import static android.os.Build.VERSION_CODES.O;
^
  symbol:   static O
  location: class
/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:112: error: cannot find symbol
        if (SDK_INT < O)
                      ^
  symbol:   variable O
  location: class Manager
/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
        ^
  symbol:   class NotificationChannel
  location: class Manager
/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:115: error: cannot find symbol
        NotificationChannel channel = mgr.getNotificationChannel(CHANNEL_ID);
                                         ^
  symbol:   method getNotificationChannel(String)
  location: variable mgr of type NotificationManager
/platforms/android/src/de/appplant/cordova/plugin/notification/Manager.java:120: error: cannot find symbol
        channel = new NotificationChannel(
                      ^
  symbol:   class NotificationChannel
  location: class Manager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
My Android SDK platforms installed:
Android API 27
Android 8.0
Android 7.1.1
Android 7.0

And on Xcode - `Version 9.0 (9A235)` : The application is built and run but i still can't display errors

About this error, maybe we should create an other issue?

Thanks.

**Comment by BeMontelli** [comment]
Config in cordova config.xml about platforms:
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="DisallowOverscroll" value="true" />
        <preference name="UIWebViewBounce" value="false" />
    </platform>
    <engine name="android" spec="^6.2.3" />
    <engine name="ios" spec="^4.4.0" />

**Comment by katzer** [comment]
@BeMontelli I think the error message is clear - you need to upgrade your compile sdk version. Even the runtime requirements are lower you need Android 8 SDK to be able to compile the code.

**Comment by katzer** [comment]
Please reopen in case of need. Thanks!
