### ISSUE TITLE
Scheduled notifications are not triggered after device reboot (Android)

### ISSUE THREAD

**Issue by djasil** [katzer/cordova-plugin-local-notifications#1449]
I'm scheduling a notification 3 minutes in the future, but it won't be triggered if I reboot the device (the system is back before the scheduled date).

The notification is still available in the system somehow, as the _isScheduled()_ function returns true for the ID I used, but for some reason it is no longer triggered.

I tested this on 3 different devices.

## Your Environment

* Plugin version: **0.9.0-beta.1**
* Platform: **Android**
* OS version: **Windows 10;  Android 7.0 / 7.1.2 / 5.0.2**
* Device manufacturer / model: **Moto G4 (XT1626) / Moto E (XT1022) / LG (LG G Pad V400)**
* Cordova version (```cordova -v```): **7.1.0**
* Cordova platform version (```cordova platform ls```): **android 6.3.0**
* Plugin config: **None (default)**
* Ionic Version (if using Ionic): **3.9.2**

## Expected Behavior

Scheduled Notifications should work, even after a device reboot.

## Actual Behavior

Scheduled Notifications are **NOT** triggered after a device reboot.

## Steps to Reproduce

  1. Schedule a notification 3 minutes in the future;
```
let scheduleDate : any = new Date(new Date().getTime() + 60000*3);

this.localNotifications.schedule({
   id: 333,
   text: 'Delayed ILocalNotification',
   at: scheduleDate,
   led: 'FF0000',
   sound: null
});

alert("Notification scheduled at "+scheduleDate);
```
  2. Reboot the system;
  3. Wait for the notification to show up;
  4. Nothing happens...

## Context

Check if a scheduled notification persists after a device reboot.

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
  * Android: $ adb logcat

**Comment by djasil** [comment]
Nevermind. It worked on the latest stable version (0.8.5).

**Comment by JohnKiller** [comment]
Isn't this a regression? On 0.8.5 works but not on latest beta... This should be fixed

**Comment by RoyeA** [comment]
+1 Have the same issue.

**Comment by katzer** [comment]
I know - The code for that is still commented out in plugin.xml due to internal changes.

**Comment by stas4000** [comment]
When do you think this feature will be available ?

**Comment by GitToTheHub** [comment]
Have the same issue :(

**Comment by wrenr** [comment]
@djasil  Per #1520, reverting back to an older more stable version of the plugin (0.8.5 release) may no longer be an effective workaround for Android 8.

As of right now, for the use case where: 

- Android 8 functionality is required
- notifications need to trigger after device restart

No plugin version is currently able to fulfill both requirements.

**Comment by Agimovel** [comment]
Not fixed? I'm in serious trouble, on latest versions it worked...but now...no notification, no error message (browser, emulator or android).

Android 6 (but need from 4.4 to 8)
Phonegap 6
Cordova-plugin-notification 0.8.5

**Comment by katzer** [comment]
Has been added to master branch. See b4631b8 - Please open again if there are still issues.

**Comment by rwillett** [comment]
Odd, I am getting this problem intermittantly  on Android 8.1.0 on a Google Pixel XL 1.

I'm using the 9.0 Beta 1 (not Beta 2) version of the plugin.

Just scheduled some code a few minutes in the future, rebooted the Android phone and we were still getting notifications appearing correctly on Android. 

Just redone the same test and it doesn't work until I start the app and then I get all the notifications. Suspect my first test was bad.

Done a third test and allowed the first of three notifications to be sent, then restarted the device, and all the notifications turned up. Not sure why we got notifications from the first test.

Will download the new master and see what it looks like.

**Comment by rwillett** [comment]
Have reopened the issue as I don't think it's resolved.

Have downloaded the latest master (I think), Beta2 and have retried the test.

Fired up the app, sent a series of notifications for a few minutes in the future, waited for first one to appear, rebooted the app and waited. I have no restarted the app. Nothing appears. 

Restart the app, put in background, and the notifications now appear.

**Comment by katzer** [comment]
Please also uninstall+reinstall the app. I had to add a permission.

**Comment by rwillett** [comment]
Ok, It'll be over the weekend.

**Comment by rwillett** [comment]
Ok, have removed and reinstalled the plugin to test if the latest version fixes the issue.

```cordova plugin rm cordova-plugin-local-notification && cordova plugin add cordova-plugin-local-notification```

I get the same behaviour as before. To recap

1.  Create a series of local notifications that will be fired over the next five mins.

2. Wait for the first one to appear.

3. Reboot the Android 8.1.0 phone. 

4. Wait for five mins expecting something to appear.

5. Nothing appears.

6. Restart the app

7. Notifications than appear.

Rob

**Comment by Agimovel** [comment]
Adding some info:

Notification on browser: doesn't work (my courses say it works, I guess they'r wrong);
On emulator: nothing
Generate apk, uninstall from smartphone, reinstall, nothing.

Scheduling or not, no error message but no notification as well.

How can I help?

**Comment by katzer** [comment]
@rwillett I tested with my device and it was working. If you connect the device with your pc and then reboot it you can monitor the output via Logcat/Android Studio. Do you see any errors related to the plugin/app?

---

> Ok, have removed and reinstalled the plugin to test if the latest version fixes the issue.

> `cordova plugin rm cordova-plugin-local-notification && cordova plugin add cordova-plugin-local-notification`

Have you installed the plugin from npm or master branch?

**Comment by rwillett** [comment]
@katzer 

I didn't check with logcat, I should have done. I didn't get any errors in Chrome but didn't dig deeper.

I install from the master branch and am not aware of how else to install. I simply type in 
```
cordova plugin rm cordova-plugin-local-notification && cordova plugin add cordova-plugin-local-notification
```

If this is wrong, apologies and let me know a better way.

Thanks

Rob

**Comment by katzer** [comment]
First remove the plugin:

    $ cordova plugin rm cordova-plugin-local-notification

Then install the latest head version:

    $ cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git

Or install from local source:

    $ cordova plugin add <path> --nofetch --nosave

**Comment by rwillett** [comment]
Ok, thats slightly different to how I do it but I thought it would be the same.

No problem, let me do that.

**Comment by wrenr** [comment]
Unfortunately the error is still happening. Full details:


## Environment

* Device manufacturer / model: Nexus 6P Huawei
* Android 8.1.0

## Expected Behavior 
Should trigger scheduled notifications after phone reboot

## Actual Behavior 
Stopped producing notifications after phone reboot. Notifications only appear as expected after opening/foregrounding the app

## Steps to Reproduce -
* installed and removed plugin to update to newest version of plugin via github URL
* Rebuild for android
* start app and schedule notification
* turn off the phone before the activation time
* turn it back on after 30 secs
* change the dateTime on the phone to a minute prior to the scheduled time

## Context

* ensuring that scheduled notifications will still trigger after rebooting the phone

**Comment by rwillett** [comment]
@katzer 

We've just tried to do the same test again, but this time using your method for reinstalling the plugin. We're still not getting any local notifications after we reboot the Android 8.0 phone. 

Looking through adb logcat is also not helping. Any ideas what we should be looking for? 

If its working for you, this should work for us for Android 8. This is simple stuff, so we're missing something :(

**Comment by GitToTheHub** [comment]
Hi,
i tested the plugin with the latest commit (#ef16347) and getting no notifications after i reboot my phone.
I have a Samsung S4 with Android 5.0.1
I saw, that my App has now the new permission, that it will be started, when the phone starts. Could it be possible, that my app must re-trigger all notifications, when the phone restarts? Or does the plugin handle this?
If i open my app after the device reboot, and the notification should have already be triggered, there will be no notification shown afterwards.
I guess, the app must retrigger all notifications, because it seems, they are all removed after the device reboot.

**Comment by katzer** [comment]
I tested again today with the new phone and it also works there...!?

```js
cordova.plugins.notification.local.schedule(
    { id: 1, text: 'Message 1', prio: 'high' },
    { id: 2, text: 'Message 2', every: 'minute' },
);
```

After reboot the message with id:2 will trigger again every minute. For none repeating notifications the plugin does only restore notifications with a prio above default (high and max).

**Comment by GitToTheHub** [comment]
Hi, i tested my notifications with the property "prio" and now all my scheduled notifications (i scheduled ~90 Notifications in the future, for April, May, June, etc.) are fired, after the device reboot, though they shouldn't be fired. Here an example:
<pre>
cordova.plugins.notification.local.schedule(
    // Fired in 2 Minutes
    { id: 1, title: 'Title 1', text: 'Message 1', trigger: { at: new Date(new Date().getTime() + (120 * 1000)) }, prio: 'high' },
    // Fired in March
    { id: 2, title: 'Title 2', text: 'Message 2', trigger: { at: new Date("2018-03-12T21:15:00") }, prio: 'high' },
    // Fired in April
    { id: 3, title: 'Title 3', text: 'Message 3', trigger: { at: new Date("2018-04-12T21:15:00") }, prio: 'high' }
);
</pre>

Additional i get warnings in the logs for the prio-property:
<pre>
[phonegap] [console.warn] Unknown property: prio
</pre>
When i'm using "priority", there will be no warning.

**Comment by katzer** [comment]
@GitToTheHub Yes you're right, good beta tester, haha. I will fix that - probably tomorrow.

**Comment by katzer** [comment]
Should be fixed now. Also with Android 7 the restoring will happen much earlier compared to Android 6 and below.

**Comment by katzer** [comment]
@rwillett For Android 8 I cannot promise that it works. I have a new phone now but no Android 8 update yet and I wont develop using the emulator...

**Comment by rwillett** [comment]
@katzer  Thats fine. I can test on my Android 8 phone and let you know.

As an aside, whats the issue with the emulator. We use the Genymotion one and it works OK. The latest Android 8 Preview image doesn't support autodownloading the Google Apps yet, but the rest of the images seem fine for average use. We use it for testing your code and for server push notifications and it works well enough for that. It does mean we can test Android 5.x,6.x and 7.x quite quickly.

Rob

**Comment by katzer** [comment]
I am doing sometimes just for a small test. But for general development the Android emulator on Mac even with HAXM is unbelievable slow and resource intensive.

**Comment by rwillett** [comment]
I don't use the HAXM emulator. I have a 32GB Mac and its painfully slow with the HAXM emulator. The Genymotion is quick enough for testing (IMHO).

**Comment by GitToTheHub** [comment]
Hi, thanks for your changes!
Now my scheduled notifications will occure, if i reboot my phone. But, they will only occure, if i leave the screen on. If i press the power button to turn the screen off, then the notification will never occure.
I'm using a Samsung S4, with power saving mode and Android 5.0.1
I noticed now, that i don't must set the priority-Property, that's good :)

**Comment by GitToTheHub** [comment]
Hi again. The notifications will occure, after the device reboot, but 4-5 minutes later. So it's all fine now.

**Comment by katzer** [comment]
Please reopen in case of need. Thanks

**Comment by NBAMj** [comment]
I tested it on OnePlus3 & Huawei Mate 9 both running `Android 8.0` and it's not working on both of them after a restart.

**Comment by GitToTheHub** [comment]
Android 8 is not fully supported yet.

**Comment by davidanaya** [comment]
Any update on this? I tested with Android 8 and notifications are not working after restarting the device, but still the thread is closed.

**Comment by marcovtwout** [comment]
@davidanaya This issue should be reopened. Also see related issue with a potential fix https://github.com/katzer/cordova-plugin-local-notifications/issues/1541

> For none repeating notifications the plugin does only restore notifications with a prio above default (high and max).

@katzer I've been looking at https://github.com/katzer/cordova-plugin-local-notifications/blob/6d1b27f1e9d8e2198fd1ea6e9032419295690c47/src/android/RestoreReceiver.java#L55. If I understand the current code correctly, one-time notifications with normal priority that are scheduled in the future will be lost on reboot. What is the purpose of the priority condition?

**Comment by davidanaya** [comment]
@marcovtwout I tested this with notifications with priority 2 (which should be the highest) and it's also not working for me.

**Comment by davidanaya** [comment]
So, I was testing the Ionic plugin, which uses beta.0.2, but if I use beta.0.3 notifications in Android 8 are working even after restart.

**Comment by marcovtwout** [comment]
@davidanaya Are you confirming on beta03 a normal priority one-time notification is rescheduled after reboot?

(Also indeed, Ionic instructions still install beta-2, to fix this we need https://github.com/katzer/cordova-plugin-local-notifications/issues/1663)

**Comment by marcovtwout** [comment]
I can also confirm this works on latest head with Android 5.1 and 8.0 - issue can remain closed.

**Comment by EnMaster** [comment]
> I can also confirm this works on latest head with Android 5.1 and 8.0 - issue can remain closed.

Not working on Android 8.1 ( cordova 7.1.0, node 8.11.1, cordova-android 6.3.0 ). Scheduled notifications are not triggered after device reboot

**Comment by marcovtwout** [comment]
@EnMaster Are you sure you're using beta03 or the latest master?

**Comment by marcovtwout** [comment]
@EnMaster Your issue might be https://github.com/katzer/cordova-plugin-local-notifications/issues/1541 instead, see https://github.com/katzer/cordova-plugin-local-notifications/pull/1611 for a potential fix.

**Comment by EnMaster** [comment]
@marcovtwout for the #1541 i don't have the AbstracRestoreReceiver.java if i will add to my project, i get this error:
`\platforms\android\src\de\appplant\cordova\plugin\notification\receiver\AbstractRestoreReceiver.java:67: error: Options(Context,JSONObject) is not public in Options; cannot be accessed from outside package	
`
