### ISSUE TITLE
Can no longer compile in Cordova 5.0.0 on Android

### ISSUE THREAD

**Issue by cvoisey** [katzer/cordova-plugin-local-notifications#535]
Is anyone else experiencing this issue?   I saw some previous posts that mentioned that the location of the files in Android have moved, however this appears to be a problem with Cordova 5.0.0.

Here is my specific error:
myDir/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
myDir/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: myDir/platforms/android/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileDebugJava FAILED

**Comment by nlinksteinar** [comment]
I also experience this error. 

It seems that the methods post(...) and evaluateJavascript(...) are removed from the Cordova 5.0.0 CordovaWebView, and that Katzer's local notification plugin hasn't been updated to reflect these changes.

**Comment by nlinksteinar** [comment]
Quick fix is to modify the block starting at LocalNotification:492 with the following:

    webView.getView().post(new Runnable(){
      public void run(){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
          webView.sendJavascript(js);
        } else {
          webView.loadUrl("javascript:" + js);
        }
      }
    });

**Comment by Krysisx** [comment]
+1

**Comment by cvoisey** [comment]
The above changed recommended by nlinksteinar worked for me!   I modified this and then re-added the Android plugin to my project and it compiled.

**Comment by cvoisey** [comment]
NOTE:  I am not comfortable modifying the code within this project to make the change permanently for others.  Perhaps someone could do that??

**Comment by Honry** [comment]
hi, all
I also reproduce this issue, and find this fix is still under review, can anyone help merged it? Would be very appreciate!

**Comment by Netronicus** [comment]
i tried to compile my code with and without crosswalk plugin with no success, i have cordova 5.0.0 and android 4.0.0, y apply the solution proposed by nlinksteinar and i can compile with no problem :D, i modified the code inside the plugin on android project, not on the root (cordova project) c:

**Comment by mix3d** [comment]
I too am experiencing the webView.evaluateJavascript issue on cordova 5.0, and the fix helps.

**Comment by 1wQasdTeedFrsweXcs234saS56Scxs5423** [comment]
webView.getView().post(new Runnable(){
  public void run(){
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      webView.sendJavascript(js);
    } else {
      webView.loadUrl("javascript:" + js);
    }
  }
});

This fix by nlinksteinar  helped.

**Comment by sharifbdp** [comment]
+1 @nlinksteinar

**Comment by jtomaszewski** [comment]
+1 @nlinksteinar 's snippet

**Comment by cagb80** [comment]
+1 for nlinksteinar... that solve the problem!!! My best...!

**Comment by biapar** [comment]
Error with Cordova 5

**Comment by Krysisx** [comment]
@katzer could you please add the @nlinksteinar 's snippet? Thanks

**Comment by cagb80** [comment]
Let me check again. I will add the snippet tomorrow! ;)

**Comment by aikivl3** [comment]
+1 @nlinksteinar 's snippet .
Thank you, nlinksteinar! you save my life brother...
Have good day!

**Comment by cagb80** [comment]
Hi the @nlinksteinar patch work in this way:

When we try to build Android Cordova App some error will marked.
Search the files with that error, search the code line with the error and replace with @nlinksteinar code:

webView.getView().post(new Runnable(){
  public void run(){
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
      webView.sendJavascript(js);
    } else {
      webView.loadUrl("javascript:" + js);
    }
  }
});

This fix 4 apps that I am creating.
TY again to @nlinksteinar for share it.

My Best!

**Comment by HuaHub** [comment]
I don't get it to work just by editing the code in the plugin (locally). If I remove and add the plugin, I'm back to where I started?

**Comment by HNygard** [comment]
+1

**Comment by artdias90** [comment]
+1 for nlinksteinar

**Comment by helsont** [comment]
+1 for nlinksteinar

**Comment by Krysisx** [comment]
+1

**Comment by AliGonabadi** [comment]
+1

**Comment by mix3d** [comment]
If you look at the latest commit, @nlinksteinar 's suggestions have been merged into master. This should be closed.

**Comment by fgarzonhz** [comment]
In 8.1 continue the error, we fixed with @nlinksteinar 's suggestions. Please add in the next release.

**Comment by murliatdure** [comment]
webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by krisrandall** [comment]
+1 for nlinksteinar

**Comment by sungwoncho** [comment]
Thanks @nlinksteinar. Using `webView.loadUrl("javascript:" + myCode);` and it works.

**Comment by homer-jay** [comment]
I'm sorry I'm a bit lost here. I understand that the `evaluateJavascript` method has been removed and therefore the need to fall back to sendJavascript. But then why are you keeping the Build.VERSION check? It is no longer needed!

**Comment by sdurandeu** [comment]
This is still failing for me on Cordova 6. Is there reliable fork I can use with the fix? Or shall I create my own?

Thanks!!

**Comment by cagb80** [comment]
@sdurandeu Now there is a new upgrade for this plugin. Use the next one: https://www.npmjs.com/package/phonegap-plugin-push

**Comment by sdurandeu** [comment]
@cagb80 Thanks! My understanding was that `phonegap-plugin-push` could only receive external notifications. Is it possible to send local notifications with it?

**Comment by Dinesh0405** [comment]
I want Local Notification when app is closed 0r killed but i am getting some problem with webView Can you Please any one help on this ???
