### ISSUE TITLE
Build Failed with Cordova 5.1.1 and Android 4.0.2

### ISSUE THREAD

**Issue by philecom** [katzer/cordova-plugin-local-notifications#618]
I get this error anytime I am building with the Local Notification plugin added to my project.
I will be glad if someone will help me resolve it. Thank you

:compileDebugJava
C:\wamp\www\inmoment\platforms\android\src\de\appplant\cordova\plugin\localnotif
ication\LocalNotification.java:495: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,<null>)
  location: variable webView of type CordovaWebView
C:\wamp\www\inmoment\platforms\android\src\de\appplant\cordova\plugin\localnotif
ication\LocalNotification.java:492: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post(<anonymous Runnable>)
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

**Comment by mix3d** [comment]
Please see the previous "does not compile" thread. There is a sort-of fix, but the latest Cordova and Android versions changed a lot of things, that this plugin does not account for.

**Comment by mix3d** [comment]
Make sure you have the latest version; there was a fix added for this 6 days ago.

**Comment by philecom** [comment]
I have tried and it is still the same
The problem is this side of the script 
  <dependency id="org.apache.cordova.device" /> I think it is suppose to be   <dependency id="apache-cordova-device" />
which is in the plugin xml file.

**Comment by akreienbring** [comment]
It seems that this plugin fails building when I update my cordova platform android to 5.x. 
On the one hand there's a dependency to "org.apache.cordova.device" which is now "cordova-plugin-device".
And on the other hand cordova 5.x requires a platform version above Android 4.0.

Has anybody resolved this? Is there a fork that is compatible with cordova 5.x?
Currently I'm stuck with cordova .4.3 because of this issue :-(

**Comment by TheMattRay** [comment]
+1

**Comment by FlossyWeb** [comment]
+1 build fails for Android only using PGB and cli-5.1.1
When I remove the plugin or if I use PG 3.7.0 it builds correctly !

**Comment by Heshyo** [comment]
I forked the plugin as of today, published it on PGB: it works with cli-5.1.1 on Android but the app does not compile on iOS (see https://github.com/katzer/cordova-plugin-local-notifications/issues/512).

**Comment by FlossyWeb** [comment]
@Heshyo when I try to build with PGB using plugin version 0.8.2 it says "plugin unsupported: de.appplant.cordova.plugin.local-notification @ 0.8.2"
What PGB plugin did you build with ?
Thanks

**Comment by Heshyo** [comment]
@FlossyWeb This plugin is only available up to 0.8.1 on PGB. I wanted to check if the current version fixes things, so I forked it and pushed my own version as **private** plugin on PGB (as to not pollute PGB with several forks of the same plugin).

**Comment by FlossyWeb** [comment]
@Heshyo @BassamTarek  Thank you guys for your answers.
This means that an update of the PGB plugin would solve this, then I'm dying to see it ;-)

**Comment by FlossyWeb** [comment]
Can someone update the plugin on the PhoneGap Build platform ? Please

**Comment by katzer** [comment]
@FlossyWeb 
> Can someone update the plugin on the PhoneGap Build platform?

Plugins cannot be submitted to PGB anymore. Use npm instead!
