### ISSUE TITLE
Can't compile in Cordova 6.0.0 on Android

### ISSUE THREAD

**Issue by salah2016** [katzer/cordova-plugin-local-notifications#875]
Is anyone else experiencing this issue? 
Here is my specific error:

100 errors
:compileDebugJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJava'.

C:...\Cordova\projects\cordova-plugin-local-notifications-example\platf
orms\android\src\de\appplant\cordova\plugin\notification\AbstractTriggerReceiver
.java:1: error: class, interface, or enum expected
.
.
.
C:...\Cordova\projects\cordova-plugin-local-notifications-example\platf
orms\android\src\de\appplant\cordova\plugin\notification\AssetUtil.java:1: error
: malformed floating point literal
.
.
.
C:\SE_Projects\Cordova\projects\cordova-plugin-local-notifications-example\platf
orms\android\src\de\appplant\cordova\plugin\notification\AssetUtil.java:1: error
: class, interface, or enum expected

thanks for ure help

**Comment by skotturi** [comment]
I can build my ionic project using Cordova CLI 6.0.0 and local-notifications plugin 0.8.2.

**Comment by rwillett** [comment]
Is this still an issue or can this be closed as its now over a year old?

**Comment by skotturi** [comment]
can be closed from my end, not sure about salah
