### ISSUE TITLE
Unable to build (cordova 3.6.3)

### ISSUE THREAD

**Issue by invalidusernam3** [katzer/cordova-plugin-local-notifications#512]
After installing the plugin, `cordova build ios` fails with the error:

`/Applications/MAMP/htdocs/app/platforms/ios/HelloCordova/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m:597:25: error: 
      use of undeclared identifier 'UIApplicationRegisterUserNotificationSettings'
                   name:UIApplicationRegisterUserNotificationSettings
1 error generated.
`

`
BUILD FAILED 
The following build commands failed:
	CompileC build/HelloCordova.build/Debug-iphonesimulator/HelloCordova.build/Objects-normal/i386/APPLocalNotification.o HelloCordova/Plugins/de.appplant.cordova.plugin.local-notification/APPLocalNotification.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: /Applications/MAMP/htdocs/app/platforms/ios/cordova/build: Command failed with exit code 65
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
`

Steps to replicate:

Create a new cordova project using `cordova project create path/to/project`
Add iOS platform using `cordova platform add ios`
Add plugin using `cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications `
Build using `cordova build ios`

**Comment by katzer** [comment]
You need to build the plugin with iOS 8 SDK

**Comment by mickeyren** [comment]
im getting this error in AppGyver with ios sdk 8.3, please any comment?

**Comment by navarrogpt** [comment]
same here

**Comment by chrisid** [comment]
same here iOS SDK 8.4

**Comment by LeBlaaanc** [comment]
Same, trying to build with AppGyver.

**Comment by MisterJack49** [comment]
Same here using vs-mda-remote

**Comment by MisterJack49** [comment]
@mickeyren did you solve your issue ?

**Comment by Heshyo** [comment]
Still getting
```
/APPLocalNotification.o
/project/LocalNotif/Plugins/com.sharinglabs.cordova.plugin.local-notification/APPLocalNotification.m:651:25: error: 
error: use of undeclared identifier 'UIApplicationRegisterUserNotificationSettings'
                   name:UIApplicationRegisterUserNotificationSettings
                        ^
1 error generated.
```
on Phonegap Build with fork on today's code (v0.8.2dev).

Is this supposed to be working with PGB on 0.8.2dev?

**Comment by MisterJack49** [comment]
With v0.8.1 it builds correctly for me so there is something broken in v0.8.2dev
